server:
  port: 8000
  tomcat:
    max-part-count: 15

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${RD_HOST}
      port: ${RD_PORT}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  batch:
    job:
      enabled: false   # Disable auto-running of jobs at startup
    jdbc:
      initialize-schema: always  # Initialize the Spring Batch schema

jwt:
  secret-key : ${JWT_SECRET_KEY}
  refresh-key : ${JWT_REFRESH_KEY}

springdoc:
  swagger-ui:
    url: /openapi.yml    # Đường dẫn public tới file YAML (qua HTTP)
    path: /swagger-ui.html
  api-docs:
    enabled: true        # Tắt tự động sinh API docs từ annotation nếu muốn

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

async:
  executor:
    core-pool-size: 8
    max-pool-size: 32
    queue-capacity: 500

